exclude: '\/migrations\/.*.py'
repos:
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
    - id: reorder-python-imports
      language_version: python3

-   repo: local
    hooks:
    - id: pyright
      name: pyright
      entry: pyright
      language: node
      pass_filenames: false
      types: [python]
      additional_dependencies: ['pyright@1.1.203']
