[tool.poetry]
name = "blurry"
version = "0.1.0"
description = "A Mistune-based static site generator for Python"
authors = ["John Franey <johnfraney@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
PyLD = "^2.0.3"
mistune = "2.0.0a6"
PyYAML = "^5.3.1"
docdata = {git = "https://github.com/waylan/docdata.git"}
Jinja2 = "^2.11.2"
livereload = "^2.6.3"
formic2 = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
