[tool.poetry]
name = "blurry"
version = "0.1.0"
description = "A Mistune-based static site generator for Python"
authors = ["John Franey <johnfraney@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
PyLD = "^2.0.3"
mistune = "2.0.0"
PyYAML = "^5.3.1"
docdata = {git = "https://github.com/waylan/docdata.git"}
Jinja2 = "^2.11.2"
livereload = "^2.6.3"
htmlmin = "^0.1.12"
typer = "^0.3.2"
Wand = "^0.6.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-watch = "^4.2.0"
pytest-cov = "^2.11.1"

[tool.poetry.scripts]
blurry = 'blurry:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
